!auto_modi:spll_window_data.D
MODULE MODI_WINDOW_DATA
INTERFACE
SUBROUTINE WINDOW_DATA(KI, B)
USE MODD_BEM_n, ONLY : BEM_t
IMPLICIT NONE
INTEGER,             INTENT(IN)  :: KI       ! number of points
TYPE(BEM_t), INTENT(INOUT) :: B
END SUBROUTINE WINDOW_DATA
END INTERFACE
END MODULE MODI_WINDOW_DATA
