# TEB version 4.0.0 (https://github.com/teb-model/teb).
# Copyright 2018 D. Meyer. Licensed under CeCILL version 2.1.

git:
  depth: false

matrix:
  include:
    - language: python
      os: linux
      dist: xenial
      python: "3.7"
      sudo: false
      env: BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - graphviz # for before_deploy
            - gfortran
    - language: python
      os: linux
      dist: xenial
      python: "3.7"
      sudo: false
      env: BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - gfortran
    - language: minimal
      os: osx
      osx_image: xcode11.2
      env: BUILD_TYPE=Debug
    - language: minimal
      os: osx
      osx_image: xcode11.2
      env: BUILD_TYPE=Release

before_install:
  - gfortran --version
  - python3 --version
  - python3 -m pip install -r requirements.txt

script:
  # We always run the integration to inform us when changes in the code also modify the outputs.
  - python3 tests/test.py --build_type=$BUILD_TYPE --case=integration

before_deploy:
  - python3 -m pip install graphviz ford
  - ford docs/api-docs.md

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: build/docs
 on:
   all_branches: true
   condition: $TRAVIS_OS_NAME = 'linux' && $BUILD_TYPE = 'Debug'