# TEB version x.x.x (https://github.com/teb-model/teb).
# Copyright 2018 D. Meyer. Licensed under CeCILL-C version 1.

matrix:
  include:
    - language: python
      os: linux
      dist: xenial
      python: "3.7"
      sudo: false
      env: BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - graphviz # for before_deploy
            - gfortran
    - language: python
      os: linux
      dist: xenial
      python: "3.7"
      sudo: false
      env: BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - gfortran
    - language: generic
      os: osx
      env: BUILD_TYPE=Debug
    - language: generic
      os: osx
      env: BUILD_TYPE=Release

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew update && brew install gcc && brew upgrade python; fi

install:
  - mkdir build && pushd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build .
  - popd

script:
  - pushd tests/CAPITOUL
  - ../../build/driver > output.log 2>&1
  - popd

before_deploy:
  - pip3 install graphviz ford
  - ford docs/api_docs.md

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: build/docs
 on:
   all_branches: true
   condition: $TRAVIS_OS_NAME = 'linux' && $BUILD_TYPE = 'Debug'