!auto_modi:spll_vslog.D
MODULE MODI_VSLOG
INTERFACE
      SUBROUTINE VSLOG(PA,PLOG,N)
      IMPLICIT NONE
      INTEGER :: N
      REAL :: PA(N), PLOG(N)
      END
END INTERFACE
END MODULE MODI_VSLOG
