!auto_modi:spll_open_namelist.D
MODULE MODI_OPEN_NAMELIST
INTERFACE
      SUBROUTINE OPEN_NAMELIST(HPROGRAM,KLUNAM,HFILE)
IMPLICIT NONE
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(OUT) :: KLUNAM   ! logical unit of namelist
 CHARACTER(LEN=28), INTENT(IN), OPTIONAL :: HFILE ! ASCII file to open
END SUBROUTINE OPEN_NAMELIST
END INTERFACE
END MODULE MODI_OPEN_NAMELIST
