!auto_modi:spll_day_of_week.D
MODULE MODI_DAY_OF_WEEK
INTERFACE
SUBROUTINE DAY_OF_WEEK(PYEAR, PMONTH, PDAY, PDOW)
IMPLICIT NONE
INTEGER,INTENT(IN) :: PYEAR !current year (UTC)
INTEGER,INTENT(IN) :: PMONTH!current month (UTC)
INTEGER,INTENT(IN) :: PDAY  !current day (UTC)
INTEGER,INTENT(OUT):: PDOW  !current day of the week
END SUBROUTINE DAY_OF_WEEK
END INTERFACE
END MODULE MODI_DAY_OF_WEEK
