!auto_modi:spll_add_forecast_to_date_surf.D
MODULE MODI_ADD_FORECAST_TO_DATE_SURF
INTERFACE
      SUBROUTINE ADD_FORECAST_TO_DATE_SURF(KYEAR,KMONTH,KDAY,PSEC)
IMPLICIT NONE
INTEGER, INTENT(INOUT) :: KYEAR  ! year of date
INTEGER, INTENT(INOUT) :: KMONTH ! month of date
INTEGER, INTENT(INOUT) :: KDAY   ! day of date
REAL,    INTENT(INOUT) :: PSEC   ! number of seconds since date at 00 UTC
END SUBROUTINE ADD_FORECAST_TO_DATE_SURF
END INTERFACE
END MODULE MODI_ADD_FORECAST_TO_DATE_SURF
