!auto_modi:spll_open_close_bin_asc_forc.D
MODULE MODI_OPEN_CLOSE_BIN_ASC_FORC
INTERFACE
      SUBROUTINE OPEN_CLOSE_BIN_ASC_FORC(HACTION,HFORCING,HACTION2)
IMPLICIT NONE
 CHARACTER(LEN=5),  INTENT(IN)  :: HACTION  ! action to do
 CHARACTER(LEN=6),  INTENT(IN)  :: HFORCING ! forcing file type
 CHARACTER(LEN=1),  INTENT(IN)  :: HACTION2 ! 'R': read, 'W': write
END SUBROUTINE OPEN_CLOSE_BIN_ASC_FORC
END INTERFACE
END MODULE MODI_OPEN_CLOSE_BIN_ASC_FORC
