!auto_modi:spll_close_file.D
MODULE MODI_CLOSE_FILE
INTERFACE
      SUBROUTINE CLOSE_FILE(HPROGRAM,KUNIT)
IMPLICIT NONE
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(IN)  :: KUNIT    ! logical unit of file
END SUBROUTINE CLOSE_FILE
END INTERFACE
END MODULE MODI_CLOSE_FILE
