!auto_modi:spll_abor1_sfx.D
MODULE MODI_ABOR1_SFX
INTERFACE
      SUBROUTINE ABOR1_SFX(YTEXT)
IMPLICIT NONE
 CHARACTER(LEN=*),  INTENT(IN)  :: YTEXT
END SUBROUTINE ABOR1_SFX
END INTERFACE
END MODULE MODI_ABOR1_SFX
