!auto_modi:spll_flag_gr_snow.D
MODULE MODI_FLAG_GR_SNOW
INTERFACE
      SUBROUTINE FLAG_GR_SNOW(KFLAG,OMASK,TPSNOW)  
USE MODD_TYPE_SNOW
IMPLICIT NONE
INTEGER, INTENT(IN) :: KFLAG ! 1 : to put physical values to run ISBA afterwards
LOGICAL, DIMENSION(:), INTENT(IN) :: OMASK ! T: points where snow values 
TYPE(SURF_SNOW), INTENT(INOUT) :: TPSNOW   ! snow characteristics
END SUBROUTINE FLAG_GR_SNOW
END INTERFACE
END MODULE MODI_FLAG_GR_SNOW
