!auto_modi:spll_close_namelist.D
MODULE MODI_CLOSE_NAMELIST
INTERFACE
      SUBROUTINE CLOSE_NAMELIST(HPROGRAM,KLUNAM)
IMPLICIT NONE
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(IN)  :: KLUNAM   ! logical unit of namelist
END SUBROUTINE CLOSE_NAMELIST
END INTERFACE
END MODULE MODI_CLOSE_NAMELIST
