!auto_modi:spll_wind_threshold.D
MODULE MODI_WIND_THRESHOLD
INTERFACE
    FUNCTION WIND_THRESHOLD(PWIND,PUREF) RESULT(PWIND_NEW)
IMPLICIT NONE
REAL, DIMENSION(:), INTENT(IN)   :: PWIND      ! wind
REAL, DIMENSION(:), INTENT(IN)   :: PUREF      ! forcing level
REAL, DIMENSION(SIZE(PWIND))     :: PWIND_NEW  ! modified wind
END FUNCTION WIND_THRESHOLD
END INTERFACE
END MODULE MODI_WIND_THRESHOLD
