!auto_modi:spll_roof_impl_coef.D
MODULE MODI_ROOF_IMPL_COEF
INTERFACE
SUBROUTINE ROOF_IMPL_COEF(T, PTSTEP, PTDEEP_A, PTDEEP_B)
USE MODD_TEB_n, ONLY : TEB_t
IMPLICIT NONE
TYPE(TEB_t), INTENT(INOUT) :: T
REAL              ,   INTENT(IN)  :: PTSTEP      ! time step
REAL, DIMENSION(:),   INTENT(OUT) :: PTDEEP_A, PTDEEP_B     
END SUBROUTINE ROOF_IMPL_COEF
END INTERFACE
END MODULE MODI_ROOF_IMPL_COEF
