!auto_modi:spll_get_luout.D
MODULE MODI_GET_LUOUT
INTERFACE
      SUBROUTINE GET_LUOUT(HPROGRAM,KLUOUT)
IMPLICIT NONE
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling GROUND
INTEGER,           INTENT(OUT) :: KLUOUT   ! Logical unit of output listing
END SUBROUTINE GET_LUOUT
END INTERFACE
END MODULE MODI_GET_LUOUT
