!auto_modi:spll_isba_snow_frac.D
MODULE MODI_ISBA_SNOW_FRAC
INTERFACE
      SUBROUTINE ISBA_SNOW_FRAC(HSNOW, PWSNOW, PRSNOW, PASNOW,       &
                                PVEG, PLAI, PZ0, PPSN, PPSNV_A, PPSNG, PPSNV )  
IMPLICIT NONE
 CHARACTER(LEN=*)    , INTENT(IN)   :: HSNOW      ! ISBA snow scheme
REAL, DIMENSION(:,:), INTENT(IN)   :: PWSNOW     ! snow reservoir
REAL, DIMENSION(:,:), INTENT(IN)   :: PRSNOW     ! snow density
REAL, DIMENSION(:)  , INTENT(IN)   :: PASNOW     ! snow albedo
REAL, DIMENSION(:)  , INTENT(IN)   :: PVEG
REAL, DIMENSION(:)  , INTENT(IN)   :: PLAI
REAL, DIMENSION(:)  , INTENT(IN)   :: PZ0
REAL, DIMENSION(:)  , INTENT(INOUT):: PPSN
REAL, DIMENSION(:)  , INTENT(INOUT):: PPSNV_A
REAL, DIMENSION(:)  , INTENT(INOUT):: PPSNG
REAL, DIMENSION(:)  , INTENT(INOUT):: PPSNV
END SUBROUTINE ISBA_SNOW_FRAC
END INTERFACE
END MODULE MODI_ISBA_SNOW_FRAC
